src/C19PUN/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
#from .views import my_home_page, about #test_list
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from pages import views as page_views

urlpatterns = [
	path('admin/', admin.site.urls),
	path('pages/', include('pages.urls')),
	path('accounts/', include('accounts.urls')),
	#path('', include(('articles2.urls', 'articles2'), namespace='article')),
	path('',page_views.pages_list, name='home'), 
	path('about/',views.about, name='about'),
	#path('test/',test_list, name='test'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
	path('signup/',views.signup_view, name='signup'),
	path('login/', views.login_view, name='login'),
	path('logout/', views.logout_view, name='logout'),

]

src/articles2/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('articles2/',views.articles_list, name="article"),
 	path('articles2/<slug:slug>/',views.article_detail, name="detail"),
]

src/pages/urls.py
from django.urls import path
from . import views

#name spacing the url by giving the name to the app.

app_name = 'pages'

urlpatterns = [
	path('',views.pages_list, name='list'),
	path('create/',views.page_create, name='create'),
	#This url is for article_details page. & In this below line we captured the slug and sent it  back via httpresponse definied in views.py of this app.
	#to understnd the URL pattern refer to https://docs.djangoproject.com/en/3.0/topics/http/urls/
	path('<slug:slug>/',views.article_detail, name='page_detail'),
]

src/accounts/models.py
from django.db import models

# Create your models here.

src/articles2/models.py
from django.db import models

# Create your models here.

class Articles(models.Model):
	title = models.CharField(max_length=200)
	slug = models.SlugField()
	body = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	thumb = models.ImageField(default='default.png',blank=True)

	def __str__ (self):
		return self.title

#model method to display limited text on the page. 

	def snippet(self):
		return self.body[:50] +'...'

src/pages/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Page(models.Model):
	title = models.CharField(max_length=100)
	slug = models.SlugField()
	body = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	thumb = models.ImageField(default='default_2.png', blank=True)
	author = models.ForeignKey(User,default=None, on_delete=models.PROTECT)

	#model method to convert object into strings.

	def __str__ (self):
		return self.title

	#model method to display limited text on the page.

	def snippet(self):
		return self.body[:50] +'...'

src/pages/forms.py
from django import forms
from .import models

class CreateArticle(forms.ModelForm):
	class Meta:
		model = models.Page
		fields = ['title', 'body', 'slug', 'thumb']

src/C19PUN/views.py
from django.http import HttpResponse
from django.shortcuts import render

def my_home_page(request):
	#return HttpResponse("Hello World")
	return render(request, 'home.html')
def about(request):
	#return HttpResponse("about")
	return render(request, 'about.html')
#def test_list(request):
#	return render(request, 'test/test_list.html')

src/accounts/views.py
from django.shortcuts import render,redirect 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm  
from django.contrib.auth import login, logout
# Create your views here.

def signup_view(request):
	#1) if its post request, then take the data from the us    er and validate it.
	if request.method =='POST':
	#we are passing in all the data into a new instance under usercreationform below.
		form = UserCreationForm(request.POST)
	#check if form is valid or invalid and save the user.
		if form.is_valid():
		# we created the user variable and save the user data in it and use this to log the user.
			user = form.save()
			login(request, user)
		

	#3) if the form is valid then we will redirect the user to page list.	
			return redirect('pages:list')
	
	#2) if the method is a get request then the below code will execute. It will take them to same signup form. This is a fresh version of the form.	
	else:
		form = UserCreationForm()
	return render(request,'accounts/signup.html',{'form': form})

def login_view(request):
	if request.method =='POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			#log the user here
			# we retrive the user from the form and then login the user.
			user = form.get_user() 
			login(request, user)

			#After we logged the user in then lets just check if next property object exisit in the POST. and redirect is to create page
			if 'next' in request.POST:
				return redirect(request.POST.get('next'))
			else: 
				return redirect('pages:list')

	else:
		form = AuthenticationForm()
	return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
	if request.method == 'POST':
		logout(request)
		return redirect('pages:list')

src/articles2/views.py
from django.shortcuts import render
from .models import Articles
from django.http import HttpResponse

# Create your views here.

def articles_list(request):
	Article = Articles.objects.all().order_by('date')
	return render(request, 'articles/articles_list.html',{ 'Article': Article })
    

def article_detail(request, slug):
	return HttpResponse(slug)
	#article = Articles.objects.get(slug=slug)
	#return render(request, 'articles/article_detail.html',{'Articles': article})

src/pages/views.py
from django.shortcuts import render, redirect
from .models import Page
from django.http import HttpResponse 
from django.contrib.auth.decorators import login_required
from .import forms

# Create your views here.

def pages_list(request):
	allpages = Page.objects.all().order_by('date')
	return render(request, 'pages/pages_list.html',{'allpages':allpages})

#query the database to find an article based on the slug.
#if it exisit we grab it send it back to the template to display the article.

def article_detail(request, slug):
	#return HttpResponse(slug)
	pagearticle = Page.objects.get(slug=slug)
	return render(request, 'pages/pages_details.html', {'mypage':pagearticle})

#this is protecting this view below. User needs to be logged in. to see the create page.

@login_required(login_url="/accounts/login")
def page_create(request):
#when we click on create button this is what its going to do.
	if request.method == 'POST':
		form = forms.CreateArticle(request.POST, request.FILES)
		if form.is_valid():
#we need to save the article based on the user. Who created this article ? this will be done below using foreign key.
			
			instance = form.save(commit=False)
			instance.author = request.user
			instance.save()
			return redirect('pages:list')
	else:
		form = forms.CreateArticle()
	return render(request, 'pages/page_create.html', {'form': form})

src/accounts/templates/accounts/login.html
{% extends 'basetemp.html' %}

{%block content%}

<h1> Login </h1>
<!-- this below given action attribute is for post request. When we hit submit button the data goes to this url below. -->
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
	{% csrf_token %}
	<!-- this below tag shows the form taken from views -->
	{{ form }} 

	<!-- We can check does the next properity(perameter) does that appear in the url any where. -->

	{% if request.GET.next %}
		<input type="hidden" name="next" value="{{ request.GET.next}}">
	{% endif %}

	<input type="submit" value="Login">
	
</form>
{% endblock %} 

src/accounts/templates/accounts/signup.html
{% extends 'basetemp.html' %}

{%block content%}

<h1> sign up </h1>
<!-- this below given action attribute is for post request. When we hit submit button the data goes to this url below. -->
<form class="site-form" action="/accounts/signup/" method="post">
	{% csrf_token %}
	<!-- this below tag shows the form taken from views -->
	{{ form }} 
	<input type="submit" value="submit">
</form>
{% endblock %} 

src/articles2/templates/articles/article_detail.html
{% extends 'basetemp.html' %}

{%block content%}

<div class="article-detail">

<div class="article">

<img src="{{Articles.thumb.url}}"/>

<h2>{{Articles.title}}</h2>

<p> {{Articles.body}}</p>


<p> {{Articles.date}}</p>

</div>
</div>
	
{% endblock %}

src/articles2/templates/articles/articles_list.html
{% extends 'basetemp.html'%}

{%block content%}

<h1> Welcome to Articles_list app </h1>

<div class="articles">
{% for article in Article %}
	<div class="article">
		<h2><a href="#">{{Articles.title}} </a></h2>
		
		<!-- <h2><a href="{% url 'article:detail' slug=Articles.slug%}">{{Articles.title}} </a></h2> -->	
		
		<p>{{Articles.snippet}}</p>
		<p>{{Articles.date}} </p>
	</div>
{%endfor %}
</div>

{% endblock %}

src/pages/templates/pages/page_create.html
{% extends 'basetemp.html' %}

{%block content%}

<div class="create-article">
	<h2>Create an Awesome new article</h2>
	<form class="site-form" action="{% url 'pages:create'%}" method="post" enctype="multipart/form-data">
		<!-- this below form is keyname from views.py -->
		{% csrf_token %}
		{{ form }}
		<input type="submit" value="create">
	</form>

</div>
<script src="/static/slugify.js"></script>

{% endblock %} 

src/pages/templates/pages/pages_details.html
{% extends 'basetemp.html' %}
{% block content %}

<div class="page-detail">
	<div class="page">
		<!-- This mypage is taken from views  -->
			<img src="{{ mypage.thumb.url }}"/>
		<!-- the page object is taken from views.py file which is mypage -->
				<h2>{{mypage.title }}</h2>
				<p>{{mypage.body }}</p>
				<p>{{mypage.date}}</p>
	</div>	
</div>

{% endblock %}

src/pages/templates/pages/pages_list.html
{% extends 'basetemp.html' %}

{% block content %}
<h1> My Pages </h1>
	<div class="pages">

	{% for Page in allpages %} 
		
		<div class="page">
			<h2><a href="{% url 'pages:page_detail' slug=Page.slug %}">{{ Page.title }}</a></h2>
			<p>{{ Page.snippet }}</p>
			<p>{{ Page.date }}</p>
			<p class="author">added by {{ Page.author.username }}</p>	
		</div>

	{% endfor %}

	</div>

{% endblock %}

src/templates/about.html
<!DOCTYPE html>
<html>
<head>
	<title>about</title>
</head>
<body>
<h1>About us </h1>
<p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</body>
</html>

src/templates/basetemp.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Articles List</title>
	<link rel="stylesheet" type="text/css" href="{% static 'styles.css'%}">

</head>

	<body>
		<header class="wrapper">
			<h1><a href="{% url 'home' %}"><img src="{% static 'logo_1.png' %}"></a></h1>	
			<nav>
				<ul>
					{% if user.is_authenticated %}
				<li>		
					<form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
					{% csrf_token %}
					<button type="submit">Logout</button>
					</form>
				</li>
				<li><a href="{% url 'pages:create'%}" class="highlight">New Article</a></li>
					{% else %}
				<li><a href="{% url 'accounts:login'%}">Login</a></li>
				<li><a href="{% url 'accounts:signup'%}">Signup</a></li>

					{% endif %}
				</ul>
			</nav>
		</header>

			<div class="wrapper">
				{% block content %}
				{% endblock %}
			</div>	
	</body> 
</html>

src/templates/home.html
<!DOCTYPE html>
<html>
<head>
	<title>PyStudyHome</title>
</head>
<body>
<h1>Welcome to python study </h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

</body>
</html>